version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14

caches:
  - &npm_cache_full v1-npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
  - &npm_cache_branch v1-npm-cache-{{ .Branch }}
  - &npm_cache_repo v1-npm-cache

commands:
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *npm_cache_full
            - *npm_cache_branch
            - *npm_cache_repo
      - run: npm ci
      - save_cache:
          key: *npm_cache_full
          paths:
            - ~/.npm
  run_code_checks:
    steps:
      - run:
          name: "Lint"
          command: "npm run lint:all"
  run_tests:
    steps:
      - run:
          name: "Test"
          command: "npm run test"

jobs:
  code_checks:
    executor: default
    steps:
      - setup_environment
      - run_code_checks
  testing:
    executor: default
    steps:
      - setup_environment
      - run_tests

workflows:
  version: 2
  build:
    jobs:
      - code_checks
      - testing:
          requires:
            - code_checks
